version: '3.4'
services:
  api:
    image: agory/cinema-api
    ports:
     - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_USER: "cinema"
      MYSQL_PASSWORD: "secret"
      MYSQL_DATABASE: "cinema"

  client:
    image: agory/cinema-client
    ports:
     - "80:5000"

